version: '3.3'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=34ab349lkk5031
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=market

  database:
    image: mysql:8
    entrypoint: ''
    command: bash -c "mysql -u user -ppassword market --host mysql < /tmp/market.sql"
    volumes:
      - ./market.sql:/tmp/market.sql
    depends_on:
      - mysql
    restart: on-failure
  
  database2:
    image: mysql:8
    entrypoint: ''
    command: >
      bash -c "
        mysql -u root -p34ab349lkk5031 --host mysql < /tmp/create-broker.sql && 
        mysql -u user -ppassword broker --host mysql < /tmp/broker.sql
      "
    volumes:
      - ./broker.sql:/tmp/broker.sql
      - ./create-broker.sql:/tmp/create-broker.sql
    depends_on:
      - mysql
    restart: on-failure

  api:
    image: maven:3.8.3-openjdk-17
    working_dir: /root/market
    command: mvn spring-boot:run
    volumes:
      - $HOME/.m2:/root/.m2
      - .:/root/market
    depends_on:
      - database
      - database2
      - mysql 
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=market
